# Generated by Django 4.0.3 on 2022-03-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('pulgadas', models.CharField(max_length=40)),
                ('resolucion', models.CharField(max_length=40)),
                ('imagen', models.ImageField(null=True, upload_to='Displays')),
                ('descripcion', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='GamingChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('sonido', models.CharField(max_length=40)),
                ('cancelacion', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='Headphones')),
                ('descripcion', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('mano', models.CharField(max_length=40)),
                ('ergonomic', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='Mouses')),
                ('descripcion', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
