# Generated by Django 4.0.3 on 2022-03-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
        migrations.DeleteModel(
            name='GamingChair',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
