# Generated by Django 4.0.3 on 2022-03-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_delete_computer_delete_gamingchair_delete_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='descripcion',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='descripcion',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='descripcion',
            field=models.TextField(max_length=120),
        ),
    ]
