# Generated by Django 4.0.3 on 2022-03-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_display_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='ergonomic',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='mano',
        ),
    ]
