# Generated by Django 4.0.3 on 2022-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_mouse_ergonomic_remove_mouse_mano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='headphone',
            name='cancelacion',
        ),
        migrations.RemoveField(
            model_name='headphone',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='display',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
    ]
